readmeai: add build patch
```
        File "/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/zipfile/__init__.py", line 412, in __init__
          raise ValueError('ZIP does not support timestamps before 1980')
      ValueError: ZIP does not support timestamps before 1980
```

Signed-off-by: Rui Chen <rui@chenrui.dev>