bacon-ls: fix audit
```
$ brew audit --new chenrui333/tap/bacon-ls
chenrui333/tap/bacon-ls
  * line 40, col 18: Use `bin/"bacon-ls"` instead of `"#{bin}/bacon-ls"`
Error: 1 problem in 1 formula detected.
```

Signed-off-by: Rui Chen <rui@chenrui.dev>